# don't change this
configversion: 4
# type database
DataBase:
  # You need to choose if you will use SQLite or Mysql or FlatFile ( default is SQLite )
  Type: flat
#MySQL config if you will use mysql ( set type to mysql )
MySQL:
  Host: localhost
  Username: root
  Password: change_this
  Port: '3306'
  Database: minecraft
# if true all debug msg will show on console
ShowDebug: false
# Enable update
UpdaterNotify: true
# Pull Mobs to location if get to far away
# this option will pull ALL mobs back 
# if this to far away !
EnablePulliFFarAway: false
# Warning don't use less then 30
# in seconds
PulliFFarAwayTime: 60
# Distance limit - Use higher values 
PulliFFarAwayLimit: 160
# Disable control over EnderDragon
DisableControlOverEnderDragon : false
# Disable the custom name for each mob
DisableCustomName : false
# Use task Check MobAlive
# Use this if you have problem 
# About Mobs Stop spawnning
# Its done 30m in 30m
# ( Develop Stage )
UseTaskCheckMobAlive : false
# Seconds with the UseTaskCheckMobAlive
# is done ( Don't lower to much )
UseTaskCheckMobAliveSeconds : 1800