name: "TimeSpawner"
version: ${project.version}
author: "Stutiguias,TheProbleemm"
main: "me.stutiguias.spawner.init.Spawner"
softdepend: [Vault,Multiverse-Core]
commands:
  sp:
    description: "§bcommands"
permissions:
     tsp.update:
        description: Allow update
        default: op
     tsp.setspawn:
        description: Allow setspawn
        default: op
     tsp.delspawn:
        description: Allow delspawn
        default: op       
     tsp.spawners:
        description: Allow spawners
        default: op
     tsp.reload:
        description: Allow reload
        default: op     
     tsp.wand:
        description: Allow wand
        default: op            
     tsp.sign:
        description: Allow create and break sign
        default: op
     tsp.tp:
        description: Teleport player to spawn name
        default: op
     tsp.reloc:
        description: Relocate all mobs back to spawn
        default: op         
     tsp.reset:
        description: Reset all mobspawn
        default: op   
     tsp.dragon.exp:
        description: get xp from enderdragons
        default: true
     tsp.dragon.unlimitedexp:
        description: allow to get xp over and over again
        default: false
     tsp.admin:
      description: Gives access to all TimeSpawner commands
      children:
        tsp.update: true
        tsp.setspawn: true
        tsp.delspawn: true
        tsp.spawners: true
        tsp.reload: true
        tsp.wand: true
        tsp.sign: true
        tsp.tp: true
        tsp.reloc: true
        tsp.reset: true